---



- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 in centos
    ansible.builtin.yum:
                     name:
                       - httpd
                       - php
                     state: latest
                     update_cache: true
    when: ansible_distribution == "CentOS"


