---

- hosts: home_server
  become: true
  tasks:

  - name: update the package repositories list
    tags: ubuntu,upgrades
    apt:
      update_cache: true

  - name: upgrade packages
    tags: ubuntu,upgrades
    apt:
      upgrade: dist

- hosts: virtual_server
  become: true
  tasks:

  - name: update the package repositories list
    tags: centos,update_only
    ansible.builtin.yum:
                      update_cache: true

  - name: upgrade packages
    tags: centos,update_only
    ansible.builtin.yum:
                      update_only: true
