- name: install apache and php package
  tags: apache,httpd,php
  package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package_name }}"
      state: latest

- name: stop the apache2
  tags: apache,httpd
  service:
      name: "{{ apache_service }}"
      state: stopped
  notify: start_apache
